CREATE TABLE ACCOUNT (
  ACCOUNT_ID  INTEGER PRIMARY KEY,
  DETAILSID VARCHAR(30)
);

CREATE TABLE USER_DETAILS (
  DETAILSID   INTEGER PRIMARY KEY,
  FNAME   VARCHAR(30),
  MNAME   VARCHAR(30),
  LNAME   VARCHAR(30)
);